name: deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0

      - name: build
        run: yarn install && yarn run build

      - name: deploy
        run: yarn deploy
